### ISSUE TITLE
Classical Radio -> DC radio

### ISSUE THREAD

**Issue by WhiskyTangoFawks** [WhiskyTangoFawks/LunarFalloutPlus#53]

**Comment by TheGreatAuz** [comment]
So I noticed this was on the nexus and I began using it as a replacement for the Diamond City radio mod you currently have in the mod list. For me it works just as well (if not better) but Travis still introduces the songs correctly instead of cutting those lines out.

https://www.nexusmods.com/fallout4/mods/56898

**Comment by WhiskyTangoFawks** [comment]
I had completely forgotten I had a DC radio mod in the list

**Comment by TheGreatAuz** [comment]
And I don't mean to impose my will or anything but I have a total wishlist type thing to add, I personally love the Atomic Radio companion to Tales from the Commonwealth, although I agree that it's strange to have an old world station still working after 200 years. If at all possible I'd add all that content into the Minutemen Radio so that people actually have a reason to listen to that station...
